imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@ProjectBundle/Resources/config/services.yml" }
    - { resource: "@UserBundle/Resources/config/services.yml" }
    - { resource: "@HomeBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    car_image_directory: '%kernel.project_dir%/web/uploads/recar/images'

#liip_imagine:
#    resolvers:
#        default:
#            web_path:
#                web_root: "%kernel.project_dir%/web/uploads/recar/images"
#                cache_prefix: /bundles/recar/images/uploads/cache
#    loaders:
#        default:
#            filesystem:
#                data_root:
#                    - "%kernel.project_dir%/web"
#                    - "%kernel.project_dir%/web/bundles/reacar/images"
#                bundle_resources:
#                    enabled: true
#    filter_sets:
#        my_thumb:
#            quality: 100
#            filters:
#                thumbnail: { size: [50, 50], mode: outbound }
#        size_two:
#            quality: 100
#            filters:
#                thumbnail: { size: [80, 80], mode: outbound }
#        size_three:
#            quality: 100
#            filters:
#                thumbnail: { size: [300, 290], mode: outbound }
#        size_four:
#            quality: 100
#            filters:
#                thumbnail: { size: [150, 150] }
#        my_thumb_default:
#            quality: 100
framework:
    templating:
        engines: [ 'twig' ]
    #esi: ~
    #translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - 'bootstrap_4_layout.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

sensio_framework_extra:
   router:
        annotations: false

assetic:
    debug:          '%kernel.debug%'
    use_controller: false
    filters:
        cssrewrite: ~
    assets:
        client_js:
            inputs:
                - 'bundles/project/js/client.js'
            output: "js/clienttemplate.js"
        recar_js:
            inputs:
                - 'bundles/project/js/car.js'
            output: "js/cartemplate.js"
        recar_home_js:
            inputs:
                - 'bundles/home/js/home.js'
            output: "js/hometemplate.js"


# api_rest Configuration
fos_rest:
    param_fetcher_listener: true
    body_listener: true
    format_listener: true
    view:
        view_response_listener: 'force'
        formats:
            xml: true
            json : true
        templating_formats:
            html: true
        force_redirects:
            html: true
        failed_validation: HTTP_BAD_REQUEST
        default_engine: twig
    routing_loader:
        default_format: json