project:
    resource: "@ProjectBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

login:
    path:     /login
    defaults: { _controller: AppBundle:Login:login }
