home_homepage:
    path:     /index
    defaults: { _controller: HomeBundle:Default:index }


cars_listing:
    path:     /cars/listing
    defaults: { _controller: HomeBundle:Default:CarsListing }

#home
home:
    path: /home
    defaults: { _controller: HomeBundle:Home:index }

#vehicule
store:
    path: /store
    defaults: { _controller: HomeBundle:Home:store }

#apropos
about:
    path: /apropos
    defaults: { _controller: HomeBundle:Home:about }

#contact
contact:
    path: /contact
    defaults: { _controller: HomeBundle:Home:contact }

#blog
blog:
    path: /blog
    defaults: { _controller: HomeBundle:Home:blog }

#singleblog
singleBlog:
    path: /blog/{id}
    defaults: { _controller: HomeBundle:Home:singleBlog }

#Conditions
conditions:
    path: /conditions
    defaults: { _controller: HomeBundle:Home:conditions }