ProjectBundle\Entity\Car:
    type: entity
    table: null
    repositoryClass: ProjectBundle\Repository\CarRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        matriclue:
            type: string
            length: 255
            unique: true
        name:
            type: string
            length: 255
        updatedAt:
            type: datetime
        createdAt:
            type: datetime
        carImage:
            mapping: carimage        # required
            filename_property: imageName  # required
#            size: imageSize
#            mime_type: imageMimeType
#            original_name: imageOriginalName
#            dimensions: imageDimensions
    lifecycleCallbacks: {  }
