ProjectBundle\Entity\Reservation:
  type: entity
  table: null
  repositoryClass: ProjectBundle\Repository\ReservationRepository
  id:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
  fields:
    startDate:
      type: datetime
    endDate:
      type: datetime
    startTime:
      type: time
    endTime:
      type: time
    daysNumber:
      type: integer
      length: 10
  manyToOne:
    client:
      targetEntity: ProjectBundle\Entity\Client
      cascade: { }
      orphanRemoval: false
  lifecycleCallbacks: {  }

