
project_homepage_admin:
    path:     /admin
    defaults: { _controller: ProjectBundle:Default:index }


index_page:
    path: /
    defaults: { _controller: ProjectBundle:Default:index }


#Car
car_add:
    path: /car/add
    defaults: { _controller: ProjectBundle:Car:add }

car_show:
    path: /car/show
    defaults: { _controller: ProjectBundle:Car:show }

car_edit:
    path: /car/edit/{id}
    defaults: { _controller: ProjectBundle:Car:edit }


#Reservation
reservation_add:
    path: /reservation/add
    defaults: { _controller: ProjectBundle:Reservation:add }

reservation_show:
    path: /reservation/show
    defaults: { _controller: ProjectBundle:Reservation:show }
