
project_homepage_admin:
    path:     /admin
    defaults: { _controller: ProjectBundle:Default:index }


index_page:
    path: /
    defaults: { _controller: ProjectBundle:Default:index }


#Car
car_add:
    path: /car/add
    defaults: { _controller: ProjectBundle:Car:add }

car_show:
    path: /car/show
    defaults: { _controller: ProjectBundle:Car:show }

car_edit:
    path: /car/edit/{id}
    defaults: { _controller: ProjectBundle:Car:edit }

car_detail:
    path: /car/detail/{id}
    defaults: { _controller: ProjectBundle:Car:detail }

#Reservation
reservation_add:
    path: /reservation/add/test
    defaults: { _controller: ProjectBundle:Reservation:add }

reservation_show:
    path: /reservation/show
    defaults: { _controller: ProjectBundle:Reservation:show }


#Client
client_add:
    path: /client/add
    defaults: { _controller: ProjectBundle:Client:add }

client_show:
    path: /client/show
    defaults: { _controller: ProjectBundle:Client:show }


client_edit:
    path: /client/edit/{id}
    defaults: { _controller: ProjectBundle:Client:edit }


#Blog
post_add:
    path: /post/add
    defaults: { _controller: ProjectBundle:Blog:add }

post_show:
    path: /post/show
    defaults: { _controller: ProjectBundle:Blog:show }

post_edit:
    path: /post/edit/{id}
    defaults: { _controller: ProjectBundle:Blog:edit }

post_list:
    path: /post/list
    defaults: { _controller: ProjectBundle:Blog:list }


#home
home:
    path: /home
    defaults: { _controller: ProjectBundle:Home:index }

#vehicule
store:
    path: /store
    defaults: { _controller: ProjectBundle:Home:store }

#apropos
about:
    path: /apropos
    defaults: { _controller: ProjectBundle:Home:about }

#contact
contact:
    path: /contact
    defaults: { _controller: ProjectBundle:Home:contact }
