project_homepage_admin:
    path:     /admin
    defaults: { _controller: ProjectBundle:Default:index }


index_page:
    path: /
    defaults: { _controller: ProjectBundle:Default:index }


#Car
car_add:
    path: /car/add
    defaults: { _controller: ProjectBundle:Car:add }

car_show:
    path: /car/show
    defaults: { _controller: ProjectBundle:Car:show }

#home
home:
    path: /home
    defaults: { _controller: ProjectBundle:Home:index }

