services:
#    project.example:
#        class: ProjectBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    car.twig_extension.carextension:
      class: ProjectBundle\Twig\CarExtension
      arguments: ["@doctrine.orm.default_entity_manager"]
      tags:
        - { name: twig.extension }
